/** Generated by scripts/gen-webp.mjs — do not edit by hand */
export type ImageMeta = { width: number; height: number; blurDataURL: string };

export const imageMeta: Record<string, ImageMeta> = {
  "/img/DSC02507.webp": {
    "width": 2800,
    "height": 1867,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAgAA4BaJZQAAp1euEV+YAD+9c8U7xR2wzN5BSaPUzs2Pqec989067xcAA=="
  },
  "/img/DSC02449.webp": {
    "width": 2800,
    "height": 4200,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoMABIAPu1iqU2ppaQiMAgBMB2JZQAAXAackxEQ/RolCgAA/uwByextJk8y+ae+JbxL0z0EfqONezyUcqk3Dt03CuJQLmkuOs4qUP0AAAA="
  },
  "/img/DSC03960.webp": {
    "width": 2800,
    "height": 1867,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoMAAgAA4BaJZQCdAEQFWCppImAAP39Pc5yiCMN0BTmsv5Su2G8AIs41QcNAAAA"
  },
  "/img/DSC02599.webp": {
    "width": 2800,
    "height": 1867,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAgAA4BaJZACdADP1rJMEADNo+U4QAwv03lZQcp/9qqpb39b/wAA"
  },
  "/img/danny.webp": {
    "width": 6014,
    "height": 4003,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAAgAA4BaJYgCdAEPDxASu4ZwAP7ph/lmsnb8Q7tdP2fwqoteyttpAuqdIBzljE62FZM+6ARmXYNw6figAA=="
  },
  "/img/DSC02862.webp": {
    "width": 2800,
    "height": 4200,
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoMABIAPu1iqU2ppaOiMAgBMB2JZACdAB6TL8cKJ9qGEQAavWkAAP7vZ5SPgHSFex5UPRFqb1qKI/+9lNTkRHXYzyYAkqUHsel1a5J4cWcOFZDMkVj+8RNNFbmz9nn7hzhpTAAA"
  },
  "/img/DSC02882.webp": {
    "width": 2800,
    "height": 4200,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoMABIAPu1iqU2ppaOiMAgBMB2JaQAAXjm90H/Qcab4pAAA/upC6M2PpBj4LNbY/CCyucHRTkzDUNkbYqVkA+SFIeL8jNAA"
  },
  "/img/DSC03950.webp": {
    "width": 2483,
    "height": 3973,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoMABMAPu1iqU2ppaQiMAgBMB2JYgCdMoACn2lMzuSBzQAA/gM36CqY4R08Cf58UQsVk6KHpnjFHkh7r1cYl8B7Qg1jA/vba2MaplSO+PGNRXDBji/7/H0AAAA="
  },
  "/img/DSC03978.webp": {
    "width": 2800,
    "height": 4200,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoMABIAPu1kqU4ppaOiMAgBMB2JaQAASlvdXB80u8wAAPrfdfs9ywxLzJh90tXZ2+yMAOIdLmCpRbX9EyoAAAAA"
  },
  "/img/bf03157f-33cc-4174-abea-14a10fada772.webp": {
    "width": 2560,
    "height": 1706,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoMAAgAA4BaJaQAAubHfDlYAP7PX4zTljeemv0xwMX4f0J372bAzvNMlBlg1P2PQUF7JpISiwAAAA=="
  },
  "/img/b3d817f9-5b13-4716-bd60-22df3db0a706.webp": {
    "width": 2514,
    "height": 1669,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAgAA4BaJaQAAuXo1ZUDAADLT7EgodQbcEU8f5xsDiwJ8rKnz6aXGBkXqlwAAAA="
  },
  "/img/edificios.webp": {
    "width": 3024,
    "height": 4032,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMABAAA4BaJYwC7ADcPMgCAAD+806ElTGnFIoFfAgFHrvh1tXTSUYAO+0e0lOuUNG4Ueh/f38sb4zKjVv4zhgAAAA="
  },
  "/img/estatua.webp": {
    "width": 1600,
    "height": 2406,
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoMABIAPu1iqU2ppaQiMAgBMB2JYwCdACK57SpbwJ/HuDE9wAD+8NW4hDRy786lLHn4PMD333kacfd6sGbXM8VC2+tbcAPjgXJ0S2t9bX7xYtwffcZJCEDKAOC6DPwr5jIAAA=="
  },
  "/img/pareja.webp": {
    "width": 1000,
    "height": 1500,
    "blurDataURL": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwAwCdASoMABIAPu1iqU2ppaOiMAgBMB2JQBOgA9BzjHXZ4dafQAD+8SDN9+JTQKjll5rX/AGxSF7z3o+3ES1jbPN3+1JUu2KRa0azjU7XaohzW4hR88Hu9J59RpNQvw4J1TVUhzKcO7bG7U27ufdGOZB3xVb4k+ug4pasytEVvjIAAAA="
  },
  "/img/faro.webp": {
    "width": 1000,
    "height": 1329,
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoMABAAA4BaJYwCdAEOZcKAAAD+FIoVLY1s2AZAqLMiJTMJmhNsAA=="
  },
  "/img/moto.webp": {
    "width": 1000,
    "height": 1500,
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQBACdASoMABIAPu1iqU2ppaOiMAgBMB2JZwDImCMDKsc/Z78+7j6+gpCAAP7pBMjfal2+VHRI6IA9l3T5xgfahHTSbSOEEWtTwEw3xgPNFgtvpxSFmAmB4fq0Xm2jjGsoVfO5/u9xatAbAAA="
  },
  "/img/barbershop.webp": {
    "width": 1080,
    "height": 1440,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMABAAA4BaJZQAAvrfqYxizAAA/viO7QN3vjKuQ6+6F5wRNVmqojknWxZhmRRT0zjSrOK3p/ZF7rgA"
  },
  "/img/cafe-de-olla.webp": {
    "width": 1080,
    "height": 1080,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAwAA4BaJbACdADbgkZ0bOgA/veCbczKCc1cUbshRKhnjwKaPddpZYqUNxNo5CU6pxE5JaEn70kel6u0kQAA"
  },
  "/img/silla-corte.webp": {
    "width": 854,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoMABIAPu1iqU2ppaOiMAgBMB2JaQAASouRkX5lTxuz4UAA/s7PwrF4SBDjPzjX7FGGAgF/e7/geQnDTEhptwO1Qdv/DJSGhybU1XxZtxQAAA=="
  },
  "/img/carros.webp": {
    "width": 1080,
    "height": 1440,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAgCdASoMABAAA4BaJYwCdAEQ/PMmOCMMAAD+ogJTcrKnGNAvq56asBTz2makLsD7RzUUYAA="
  }
};

export function metaFor(src: string): ImageMeta {
  const m = imageMeta[src];
  if (!m) throw new Error(`missing image meta: ${src}`);
  return m;
}
