/** ponytail: one-shot build script; re-run after adding gallery photos */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const IMG = path.join(ROOT, "public", "img");

const SOURCES = [
  "DSC02507.jpg",
  "DSC02449.jpg",
  "DSC03960.jpg",
  "DSC02599.jpg",
  "danny.jpg",
  "DSC02862.jpg",
  "DSC02882.jpg",
  "DSC03950.jpg",
  "DSC03978.jpg",
  "bf03157f-33cc-4174-abea-14a10fada772.jpg",
  "b3d817f9-5b13-4716-bd60-22df3db0a706.jpg",
  "edificios.jpeg",
  "estatua.jpg",
  "pareja.jpeg",
  "faro.jpg",
  "moto.jpeg",
  "barbershop.jpg",
  "cafe-de-olla.jpg",
  "silla-corte.jpeg",
  "carros.jpg",
];

const meta = {};
let before = 0;
let after = 0;

for (const file of SOURCES) {
  const src = path.join(IMG, file);
  if (!fs.existsSync(src)) {
    console.warn(`skip missing: ${file}`);
    continue;
  }

  before += fs.statSync(src).size;
  const webpName = file.replace(/\.(jpe?g)$/i, ".webp");
  const dest = path.join(IMG, webpName);

  const pipeline = sharp(src);
  const { width, height } = await pipeline.metadata();
  await pipeline.webp({ quality: 88, effort: 4 }).toFile(dest);

  after += fs.statSync(dest).size;

  const blurBuf = await sharp(dest).resize(12, Math.round(12 * (height / width)), { fit: "inside" }).webp({ quality: 40 }).toBuffer();
  const key = `/img/${webpName}`;
  meta[key] = { width, height, blurDataURL: `data:image/webp;base64,${blurBuf.toString("base64")}` };

  fs.unlinkSync(src);
  console.log(`${file} → ${webpName} (${Math.round(fs.statSync(dest).size / 1024)} KB)`);
}

const out = `/** Generated by scripts/gen-webp.mjs — do not edit by hand */\nexport type ImageMeta = { width: number; height: number; blurDataURL: string };\n\nexport const imageMeta: Record<string, ImageMeta> = ${JSON.stringify(meta, null, 2)};\n\nexport function metaFor(src: string): ImageMeta {\n  const m = imageMeta[src];\n  if (!m) throw new Error(\`missing image meta: \${src}\`);\n  return m;\n}\n`;

fs.writeFileSync(path.join(ROOT, "lib", "image-meta.ts"), out);

console.log(`\nBefore: ${Math.round(before / 1024)} KB (${(before / 1048576).toFixed(2)} MB)`);
console.log(`After:  ${Math.round(after / 1024)} KB (${(after / 1048576).toFixed(2)} MB)`);
console.log(`Saved:  ${Math.round((before - after) / 1024)} KB (${(((before - after) / before) * 100).toFixed(1)}%)`);
